// Firebase configuration helper generated by the FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Platform-specific Firebase options supported by the app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZr_7B58vJeqr83iCpIcWIhsogr93Jy1g',
    appId: '1:662438044608:web:641b7703a26446ea161e25',
    messagingSenderId: '662438044608',
    projectId: 'andante-resort-211b3',
    authDomain: 'andante-resort-211b3.firebaseapp.com',
    storageBucket: 'andante-resort-211b3.firebasestorage.app',
    measurementId: 'G-3GQ41JNMXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcOCqXyWCeN4Ad4-9ZerHesO7xvTIT-YY',
    appId: '1:662438044608:android:a75d263909915f60161e25',
    messagingSenderId: '662438044608',
    projectId: 'andante-resort-211b3',
    storageBucket: 'andante-resort-211b3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3z1vEfZ333EQrF5NTsiowJDqHirelZKw',
    appId: '1:662438044608:ios:e4cf70d353e2ef01161e25',
    messagingSenderId: '662438044608',
    projectId: 'andante-resort-211b3',
    storageBucket: 'andante-resort-211b3.firebasestorage.app',
    iosBundleId: 'com.example.andanteResortApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3z1vEfZ333EQrF5NTsiowJDqHirelZKw',
    appId: '1:662438044608:ios:e4cf70d353e2ef01161e25',
    messagingSenderId: '662438044608',
    projectId: 'andante-resort-211b3',
    storageBucket: 'andante-resort-211b3.firebasestorage.app',
    iosBundleId: 'com.example.andanteResortApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZr_7B58vJeqr83iCpIcWIhsogr93Jy1g',
    appId: '1:662438044608:web:966c4fc872466cab161e25',
    messagingSenderId: '662438044608',
    projectId: 'andante-resort-211b3',
    authDomain: 'andante-resort-211b3.firebaseapp.com',
    storageBucket: 'andante-resort-211b3.firebasestorage.app',
    measurementId: 'G-H43NJ6Q44L',
  );
}
